---
#
# Playbook setup Pi nextcloud
#
- name: Pi NextCloud setup
  hosts: nextcloud
  gather_facts: yes
  become: yes

  tasks:
    - import_role:
        name: pi
    - import_role:
        name: nextcloud