---
# Setup backup to onedrive

- name: Create /var/log/ncbkup dir
  file:
    name: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
  loop:
    - /var/log/ncbkup
    - /var/log/ncbkup/logs

- name: Install /usr/local/bin/ncbkup script
  copy:
    src: files/ncbkup.sh
    dest: /usr/local/bin/ncbkup
    owner: www-data
    group: www-data
    mode: 0766

- name: Install /etc/ncbkup.exclude
  copy:
    src: files/ncbkup.exclude
    dest: /etc/ncbkup.exclude
    owner: www-data
    group: www-data
    mode: 0644

- name: Setup bkup cron job
  cron:
    name: "backup nextcloud"
    minute: "5"
    hour: "1"
    job: "/usr/local/bin/ncbkup -b > /dev/null"
    user: www-data
    disabled: yes