---
# Mount /dev/sda1

- name: Mount /mnt/nc1
  mount:
    path: /mnt/nc1
    src: UUID=09c318d5-b23a-4ec0-8327-6d6296fae7a0
    fstype: ext4
    state: mounted

- name: Add pi to www-data group
  user:
    name: pi
    groups: www-data
    append: yes