---
# NextCloud required PHP packages

- name: Install required PHP packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "php{{ php_version }}-gd"
    - "php{{ php_version }}-mysql"
    - "php{{ php_version }}-curl"
    - "php{{ php_version }}-mbstring"
    - "php{{ php_version }}-intl"
    - "php{{ php_version }}-gmp"
    - "php{{ php_version }}-bcmath"
    - "php{{ php_version }}-imagick"
    - "php{{ php_version }}-xml"
    - "php{{ php_version }}-zip"
    - "php{{ php_version }}-apcu"
    - libmagickcore-6.q16-6-extra

- name: Enable PHP {{ php_version }} modules
  command: phpenmod "{{ item }}"
  args:
    creates: "/etc/php/{{ php_version }}/cli/conf.d/20-{{ item }}.ini"
  loop:
    - bcmath
    - gmp
    - intl
    - imagick

- name: Set php_ini_path variable
  set_fact:
    php_ini_path: "/etc/php/{{ php_version }}/apache2/php.ini"

- name: Set PHP ini values
  ini_file:
    path: "{{ php_ini_path }}"
    section: PHP
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ ini_data | dict2items }}"
  vars:
    ini_data:
      memory_limit: 512M
      upload_max_filesize: 20G
      max_execution_time: 360
      post_max_size: 20G
      date.timezone: Pacific/Auckland
      opcache.enable: 1
      opcache.interned_strings_buffer: 16
      opcache.max_accelerated_files: 10000
      opcache.memory_consumption: 128
      opcache.save_comments: 1
      opcache.revalidate_freq: 60
  notify:
  - restart apache2