---
# NextCloud required PHP packages

- name: Install required PHP packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - php7.4-gd
    - php7.4-mysql
    - php7.4-curl
    - php7.4-mbstring
    - php7.4-intl
    - php7.4-gmp
    - php7.4-bcmath
    - php-imagick
    - php7.4-xml
    - php7.4-zip
    - php7.4-apcu
    - libmagickcore-6.q16-6-extra

- name: Enable PHP 7.4 modules
  command: phpenmod "{{ item }}"
  args:
    creates: "/etc/php/7.4/cli/conf.d/20-{{ item }}.ini"
  loop:
    - bcmath
    - gmp
    - intl
    - imagick

- name: Set php_ini_path variable
  set_fact:
    php_ini_path: /etc/php/7.4/apache2/php.ini

- name: Set PHP ini values
  ini_file:
    path: "{{ php_ini_path }}"
    section: PHP
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ ini_data | dict2items }}"
  vars:
    ini_data:
      memory_limit: 512M
      upload_max_filesize: 200M
      max_execution_time: 360
      post_max_size: 200M
      date.timezone: Pacific/Auckland
      opcache.enable: 1
      opcache.interned_strings_buffer: 16
      opcache.max_accelerated_files: 10000
      opcache.memory_consumption: 128
      opcache.save_comments: 1
      opcache.revalidate_freq: 60
  notify:
  - restart apache2