---
# Mount /dev/sda1 as bkup disk

- name: Install exFatProgs
  apt:
    name: exfatprogs
    state: present

- name: Mount /mnt/t7
  mount:
    path: /mnt/t7
    src: UUID=365A-9B5D
    fstype: exfat
    opts: "defaults,auto,umask=000,users,rw,uid={{ ansible_user }},gid={{ ansible_user }}"
    state: mounted

- name: Create /mnt/t7/onedrv_bkup
  file:
    path: /mnt/t7/onedrv_bkup
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0750