---
# Setup onedrive bkup

- name: Create /home/{{ ansible_user }}/odbkup dir
  file:
    name: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - /home/{{ ansible_user }}/odbkup
    - /home/{{ ansible_user }}/odbkup/logs

- name: Install /home/{{ ansible_user }}/odbkup/odbkup.sh script
  copy:
    src: files/odbkup.sh
    dest: /home/{{ ansible_user }}/odbkup/odbkup.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0766

- name: Install /home/{{ ansible_user }}/odbkup/odbkup.exclude
  copy:
    src: files/odbkup.exclude
    dest: /home/{{ ansible_user }}/odbkup/odbkup.exclude
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Setup bkup cron job
  cron:
    name: "backup onedrive"
    minute: "5"
    hour: "1"
    job: "/home/{{ ansible_user }}/odbkup/odbkup.sh -b > /dev/null"
    user: "{{ ansible_user }}"
#    disabled: yes