---
# Setup pi WireGuard VPN
# Refer README.md
#

- import_tasks: ufw.yml
  tags: ufw

- import_tasks: pivpn.yml
  tags: pivpn

- import_tasks: wg.yml
  tags: wg

- import_tasks: clients.yml
  tags: clients

- import_tasks: unattended_upgrades.yml
  tags: unattended

- import_tasks: bkup_disk.yml
  tags: bkup_disk

- import_tasks: rclone.yml
  tags: rclone

- import_tasks: mutt.yml
  tags: mutt

- import_tasks: bkup.yml
  tags: bkup

- import_tasks: ssh_keys.yml
  tags: sshkeys

- import_tasks: smb.yml
  tags: smb

#- import_tasks: minidlna_uninstall.yml
#  tags: minidlna