---
# install authorised keys

- name: Add linco minipc authorised key
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ item.key }}"
  loop: "{{ authorized_keys }}"