---
# Build OpenCV using gocv make file

- name: Install git
  apt:
    name: git
    state: present
  become: yes

- name: Install screen
  apt:
    name: screen
    state: present
  become: yes

- name: Copy make_gocv.sh to /home/pi
  copy:
    src: files/make_gocv.sh
    dest: /home/pi/make_gocv.sh
    mode: '0755'
    owner: pi
    group: pi

# Leaves a gocv_make.flag file if new module downloaded. So next task can detect the make steps need to run.
- name: Check and download latest gocv module. Run/home/pi/make_gocv.sh -u
  shell: "/home/pi/make_gocv.sh -u"
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin"
  changed_when: false

# Runs a detached screen in the background, to asynchonously build gocv.
# Script only runs if the new module signal file exists.
# Script runs only the make steps that haven't completed sucessfully.
# Task will fail if rerun while a previous execution is still running. I.e. checks if the screen process exists. 
- name: Run /home/pi/make_gocv.sh (Takes a long time. Runs as a detached screen)
  shell: "/home/pi/make_gocv.sh -b"
  args:
    executable: /bin/bash
    removes: "/home/pi/gocv_make.flag"
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin"

- name: Create godev directories
  file:
    path: "/home/pi/godev/version"
    mode: '0755'
    state: directory

- name: Copy version.go example
  copy:
    src: files/version.go
    dest: /home/pi/godev/version/main.go
    mode: '0644'
    owner: pi
    group: pi

# Need to do a "go get gocv.io/x/gocv" to add to go.mod file but can't do this until the make steps are complete.
- name: Init version modules
  shell: "go mod init examples.com/version"
  args:
    executable: /bin/bash
    chdir: "/home/pi/godev/version"
    creates: "/home/pi/godev/version/go.mod"
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin"
