---
# Disable Wifi and/or Bluetooth wireless

- name: Check if /boot/firmware/config.txt exists
  stat:
    path: /boot/firmware/config.txt
  register: new_config_txt

- name: Disable wireless
  block:
  - name: Insert disable wireless comment into {{ configfile }}
    lineinfile:
      path: "{{ configfile }}"
      line: "{{ comment_line }}"
      state: present
  - name: Disable wifi radio via {{ configfile }}
    lineinfile:
      path: "{{ configfile }}"
      line: "dtoverlay=disable-{{ item }}"
      insertafter: "{{ comment_line }}"
      state: present
    loop:
      - wifi
      - bt
    notify:
      - Show allow_reboots
      - Reboot
  vars:
    comment_line: "# LG - Ansible Disable wireless"
    configfile: "{{ '/boot/firmware/config.txt' if new_config_txt.stat.exists else '/boot/config.txt' }}"
  when: pi_disable_wireless == True