---
# Install packages

- name: Install basic software
  package:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - neofetch

- name: Add neofetch to .bashrc
  ansible.builtin.lineinfile:
    path: .bashrc
    line: neofetch
    insertafter: EOF
    state: present