---
# Secure the pi account with a strong password
#
- name: "{{ ansible_user }} user password info"
  debug:
    msg:
    - "Password Hash: {{ pi_password_hash }}"
    verbosity: 1

- name: Set {{ ansible_user }} password
  user:
    name: "{{ ansible_user }}"
    password: "{{ pi_password_hash }}"
  when: ansible_become_password is undefined